baseURL = "https://0xqige.eth.limo"
defaultContentLanguage = "en"
enableEmoji = true
languageCode = "en"
paginate = 20
theme = "hugo-coder"
title = "七哥"
uglyURLs = true

# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
author = "七哥"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
avatarURL = "images/avatar.jpg"
description = "七哥's personal web site"
info = ["Blockchain Developer", "DeFi&AA"]
keywords = "blog,developer,personal,blockchain,ethereum,web3,defi,decentralized finance,decentralized applications,decentralized exchange,decentralized identity,decentralized storage,decentralized autonomous organization,decentralized autonomous corporation,decentralized autonomous cooperative,decentralized autonomous community,decentralized autonomous company,decentralized autonomous organization,decentra"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2023
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/0xqige/0xqige.eth/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
# outboundLinksTracking = true
# fileDownloadsTracking = true

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to use Yandex Metrika(https://metrika.yandex.ru) for analytics, add this section
# [params.yandexMetrika]
# id = "gid"

# If you want to use Application Insights(https://azure.com/) for analytics, add this section
# [params.applicationInsights]
# connectionString = "connectionString"

# If you want to use microanalytics.io for analytics, add this section
# [params.microAnalytics]
# id = "ABCDE"
# dnt = "false" # respect DNT tracker, "true" by default

# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'", "https://www.youtube.com"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/",
# ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[[params.social]]
icon = "fa fa-2x fa-github"
name = "Github"
url = "https://github.com/0xqige/"
weight = 1

[[params.social]]
icon = "fa fa-2x fa-gitlab"
name = "Gitlab"
url = "https://gitlab.com/0xqige/"
weight = 2

[[params.social]]
icon = "fa fa-2x fa-twitter"
name = "Twitter"
url = "https://twitter.com/0xqige/"
weight = 3

# [[params.social]]
# icon = "fa fa-2x fa-linkedin"
# name = "LinkedIn"
# url = "https://www.linkedin.com/in/johndoe/"
# weight = 4

# [[params.social]]
# icon = "fa fa-2x fa-medium"
# name = "Medium"
# url = "https://medium.com/@johndoe"
# weight = 5

[[params.social]]
icon = "fa fa-2x fa-rss"
name = "RSS"
rel = "alternate"
type = "application/rss+xml"
url = "https://0xqige.eth.limo/index.xml"
weight = 6

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
url = "about.html"
weight = 1

[[languages.en.menu.main]]
name = "Blog"
url = "posts.html"
weight = 2

[[languages.en.menu.main]]
name = "Projects"
url = "projects.html"
weight = 3

[[languages.en.menu.main]]
name = "Contact"
url = "contact.html"
weight = 5

# [languages.pt-br]
# languageName = ":brazil:"
# title = "João Ninguém"
